server:
  port: 8080
spring:
  datasource:
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.53.91:3305/yhp?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: syn123
    # 使用druid数据源
    type: com.mysql.cj.jdbc.MysqlDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
